### ISSUE TITLE
How should i use it on Windows？

### ISSUE THREAD

**Issue by EthanCodesss** [tom-doerr/carla_rl_weights#1]
How should i use it on Windows？Thank you！

**Comment by tom-doerr** [comment]
The easiest way would be to use the Windows Subsystem for Linux with Ubuntu.

**Comment by EthanCodesss** [comment]
> The easiest way would be to use the Windows Subsystem for Linux with Ubuntu.

Thank you very much!! I just saw your reply, but I got the following error:
Not an lrzip file
Fatal error - exiting
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

What should i do?

**Comment by tom-doerr** [comment]
Do you get the error for both files?

**Comment by EthanCodesss** [comment]
I don't think I did. I followed the read me exactly.

**Comment by tom-doerr** [comment]
Okay, I just check it and I get the same error. I think the issue is that I added those files using git LFS, so you either have to install git LFS and then clone the repository again or you could just download the files directly through the Github web interface.

**Comment by EthanCodesss** [comment]
> Do you get the error for both files?

Ubuntu 20.04 subsystem is what i use,then i install the lrzip. But it doesn't work.

**Comment by EthanCodesss** [comment]
I just download the files directly through the Github web interface before,but it seems doesn't work. I will try git LFS.

**Comment by tom-doerr** [comment]
Just downloaded them with git LFS installed, that worked for me.

**Comment by EthanCodesss** [comment]
> Just downloaded them with git LFS installed, that worked for me.

Okay. Thanks again for your reply!!

**Comment by EthanCodesss** [comment]
> Just downloaded them with git LFS installed, that worked for me.

Hey man，I tried to use the git clone to download it, but it was very slow and always broke.Would you mind uploading a copy to Google Drive?

**Comment by tom-doerr** [comment]
Here you go: https://drive.google.com/drive/folders/1O5vxxT4V1EoduDrdGgwEXKe2-ag1uCiQ?usp=sharing

**Comment by EthanCodesss** [comment]
> Here you go: https://drive.google.com/drive/folders/1O5vxxT4V1EoduDrdGgwEXKe2-ag1uCiQ?usp=sharing

Many thanks for your kind and warm help!!!
